// ============================================================
// Data Layer — every tool, stage, checklist, incident
// ============================================================

// ---- 5-TIER PYRAMID --------------------------------------------------
const TIERS = [
  {
    n: 5,
    name: "Autonomous Agents",
    tag: "High Power · Unpredictable",
    use: "Long-horizon, async, multi-day work you supervise loosely.",
    when: "When you can spec a task clearly and walk away for hours.",
    risks: "Spends credits fast. Hallucinates dependencies. Needs review gates.",
    tools: ["Devin", "Manus", "OpenClaw", "NVIDIA NeMo", "OpenAI Codex Cloud"],
  },
  {
    n: 4,
    name: "Power Workflows",
    tag: "Scale Fast",
    use: "Multi-file refactors, scripted automations, terminal-native flows.",
    when: "You can read code and want the AI to do the heavy typing.",
    risks: "Token spirals on long sessions. Needs explicit context curation.",
    tools: ["Claude Code", "Warp.dev", "Aider", "Gemini CLI"],
  },
  {
    n: 3,
    name: "AI Editors",
    tag: "Best Value · The Default",
    use: "Daily driver IDE with AI Tab, Composer, codebase context.",
    when: "You write code regularly — this is where most builders live.",
    risks: "Credit/token pricing can spiral. You still own the code.",
    tools: ["Cursor", "Windsurf", "GitHub Copilot", "Trae", "Zed"],
  },
  {
    n: 2,
    name: "Vibe Platforms",
    tag: "Validate Ideas",
    use: "Prompt → full-stack app in a browser tab. Auth, DB, deploy included.",
    when: "Going from idea → demo in a weekend, MVPs, prototypes.",
    risks: "Code quality varies. RLS/secrets often misconfigured. Audit before launch.",
    tools: ["Lovable", "Bolt.new", "Replit", "v0 by Vercel", "Rork", "Base44", "Emergent"],
  },
  {
    n: 1,
    name: "Chatting with AI",
    tag: "Fast Website · No Setup",
    use: "Describe the page, paste the code, ship.",
    when: "Landing page, one-off scripts, learning, throwaway experiments.",
    risks: "No environment, no persistence — copy/paste discipline required.",
    tools: ["Claude", "ChatGPT", "Manus", "Gemini", "Grok"],
  },
];

// ---- ICEBERG ---------------------------------------------------------
const ICEBERG_VIBE = {
  above: ["Lovable", "Bolt", "Cursor", "v0", "Replit", "Windsurf"],
  tagline: "What you ship in a weekend",
};
const ICEBERG_PROD = {
  huge: ["Authentication", "Payments"],
  lg: ["Scalability", "Logging", "CI/CD", "Conversion", "Retention"],
  md: [
    "Billing logic", "Subscription states", "CRUD logic", "Access control",
    "Data integrity", "Latency optimization", "Load balancing", "Alerting",
    "Incident response", "Disaster recovery", "Data retention", "GDPR/CCPA",
    "Rate limiting", "Environments", "Rollbacks", "Feature flags",
    "Test coverage", "Instrumentation", "Churn control", "Cloud costs",
    "Multi-region support", "Idempotency", "Support ops", "Escalations",
    "Governance", "Platform support", "Adtech", "Cookies",
    "Secrets management", "Documentation", "A/B testing", "Vendor lock-in",
    "Row-level security", "Webhook verification", "PII masking",
    "Quota enforcement", "Audit logs",
  ],
};

// ---- ROADMAP STAGES --------------------------------------------------
const STAGES = [
  {
    id: "ideate",
    stage: "00",
    name: "Ideate",
    time: "1–3 days",
    persona: "You + a doc",
    cost: "$0",
    goal: "Pin down the one problem worth solving. Sketch the smallest possible thing that would prove it.",
    tools: [
      { nm: "Claude", ds: "Think out loud, sharpen the brief", px: "Pro $20/mo" },
      { nm: "ChatGPT", ds: "Competitive scan, persona prompts", px: "Plus $20/mo" },
      { nm: "Manus", ds: "Wide research agent", px: "Free / $20" },
      { nm: "Excalidraw", ds: "Whiteboard the user flow", px: "Free" },
      { nm: "Whimsical", ds: "Lo-fi screen flow", px: "Free / $12" },
      { nm: "Notion", ds: "One-pager brief", px: "Free" },
    ],
    do: [
      { t: "Write a 1-page brief", d: "Problem · user · jobs-to-be-done · success metric. Don't skip this." },
      { t: "Map 3 user flows", d: "Signup, core action, monetization. Stick figures are fine." },
      { t: "Spec the data model", d: "Tables, relationships, who-owns-what. AI tools cargo-cult this badly if you don't." },
      { t: "Decide the wedge", d: "One niche, one persona, one core loop. Resist scope creep." },
    ],
    deliver: ["1-page PRD", "Flow sketches", "Data model napkin"],
    pitfall: "Skipping the brief and going straight to a vibe platform. You will burn 4× the credits iterating on something you haven't defined.",
  },
  {
    id: "prototype",
    stage: "01",
    name: "Prototype",
    time: "1–7 days",
    persona: "Non-tech founder OR dev",
    cost: "$0 – $25",
    goal: "Get a clickable, shareable URL in front of 5 humans. Optimize for screenshot quality, not robustness.",
    tools: [
      { nm: "Lovable", ds: "Best UI polish, Supabase-native", px: "Free / $25 / $100" },
      { nm: "Bolt.new", ds: "Fastest browser → app, WebContainer", px: "Free / $20" },
      { nm: "v0 by Vercel", ds: "React + shadcn UI components", px: "Free / $20" },
      { nm: "Replit Agent", ds: "Browser IDE + agent, broad stacks", px: "Free / $25" },
      { nm: "Rork", ds: "Mobile-first prompts → Expo apps", px: "Free / $20" },
      { nm: "Base44", ds: "Enterprise-leaning app builder", px: "Free / $20" },
      { nm: "Emergent", ds: "Multi-agent full-product builder", px: "$20+" },
      { nm: "Tempo Labs", ds: "Design-first React builder", px: "$25+" },
    ],
    do: [
      { t: "Pick ONE platform", d: "Lovable if non-technical · Bolt if technical & visual · v0 if you're already on Next.js/Vercel." },
      { t: "Prompt the data model first", d: "Paste your napkin. Make the AI generate the schema before any UI." },
      { t: "Build the happy path only", d: "Signup → core action → success screen. Skip settings, password reset, edge cases." },
      { t: "Ship to a public URL same day", d: "All three platforms give you one. Send it to 5 friends." },
    ],
    deliver: ["Public preview URL", "Happy-path demo", "GitHub repo (export early!)"],
    pitfall: "Falling in love with the UI and trying to make it 'production' inside Lovable/Bolt. These tools optimize for demo, not for the iceberg. Move down-stack when validated.",
  },
  {
    id: "build",
    stage: "02",
    name: "Build",
    time: "1–4 weeks",
    persona: "Dev or dev-curious",
    cost: "$20 – $60/mo",
    goal: "Take the prototype off the vibe platform. Own the code in a real editor. Add the features that make it actually useful.",
    tools: [
      { nm: "Cursor", ds: "Default AI IDE, $20/mo Pro", px: "Free / $20 / $40" },
      { nm: "Windsurf", ds: "Codeium's IDE, flat pricing", px: "Free / $15" },
      { nm: "Claude Code", ds: "Terminal agent, multi-file work", px: "Bundled w/ Claude" },
      { nm: "GitHub Copilot", ds: "Cheapest, IDE-agnostic", px: "$10 / $19" },
      { nm: "Aider", ds: "Open-source CLI pair", px: "Free + API" },
      { nm: "Cline", ds: "VS Code agent, BYO key", px: "Free + API" },
      { nm: "Voibe", ds: "Voice → prompt input layer", px: "$99 lifetime" },
      { nm: "Zed", ds: "Fast collab editor + AI", px: "Free" },
    ],
    framework: ["Next.js 15 (App Router)", "Expo (React Native)", "Astro (content)", "SvelteKit"],
    do: [
      { t: "Export from the vibe platform", d: "Connect GitHub from Lovable/Bolt. Clone locally. You own the code now." },
      { t: "Open in Cursor (or Claude Code)", d: "Index the codebase. Read the auth & DB code yourself — that's the 70% the audit will fail on." },
      { t: "Add the un-fun screens", d: "Settings, password reset, 404, error boundary, empty states, loading states." },
      { t: "Wire real third-party SDKs", d: "Replace mock data. Use server-side keys only." },
    ],
    deliver: ["Local dev environment", "Real auth & DB", "All non-happy-path screens", "Git history with meaningful commits"],
    pitfall: "Asking the AI to 'fix the bug' across 12 files without ever reading the code. You'll ship a Rube Goldberg fix and break two things. Curate context.",
  },
  {
    id: "harden",
    stage: "03",
    name: "Harden",
    time: "1–2 weeks",
    persona: "You + audit",
    cost: "$0 – $3,000",
    goal: "Cross the water line. Fix the things the vibe platform never asked about: auth, RLS, secrets, payments, rate limits.",
    tools: [
      { nm: "Supabase", ds: "Postgres + Auth + Storage + RLS", px: "Free / $25" },
      { nm: "Clerk", ds: "Auth-as-a-service, drop-in", px: "Free / $25" },
      { nm: "Auth0", ds: "Enterprise auth", px: "Free / $35+" },
      { nm: "Stripe", ds: "Payments, billing, subscriptions", px: "2.9% + 30¢" },
      { nm: "Lemon Squeezy", ds: "Merchant of record, handles tax", px: "5% + 50¢" },
      { nm: "Upstash Redis", ds: "Rate limiting, queues", px: "Free / $10+" },
      { nm: "TruffleHog", ds: "Scan git history for secrets", px: "Free" },
      { nm: "Snyk Code / Aikido", ds: "Static analysis, dependency audit", px: "Free / $25" },
      { nm: "Escape.tech", ds: "Vibe-code-specific scanner", px: "Free tier" },
      { nm: "Dependabot", ds: "GitHub auto dependency PRs", px: "Free" },
    ],
    do: [
      { t: "Run a vibe-code audit", d: "DIY checklist or pro ($500–$3k). Most apps ship with 8–14 findings; 70% of Lovable apps have broken RLS." },
      { t: "Move every secret to env vars", d: "Search for sk-, api_key, token. Rotate any key that ever touched git. NEXT_PUBLIC_ and VITE_ prefixes are PUBLIC." },
      { t: "Enable RLS on every table", d: "Default 'allow all' is the demo cheat. Write policies per table. Test with anon role." },
      { t: "Validate payments server-side", d: "Never trust frontend price. Verify Stripe webhooks with signing secret. Idempotency keys on charge." },
      { t: "Add rate limiting + error boundaries", d: "Upstash + middleware. Generic error pages — no stack traces in prod." },
    ],
    deliver: ["Audit report (0 critical)", "All secrets in vault", "RLS on every table", "Stripe webhooks verified", "Rate limits on every public endpoint"],
    pitfall: "Skipping this stage because 'it works'. Veracode tested 100+ models: 45% of AI-generated code has OWASP Top 10 vulns. Aikido attributes 1 in 5 enterprise breaches to AI code. This is not optional.",
  },
  {
    id: "deploy",
    stage: "04",
    name: "Deploy",
    time: "1–3 days",
    persona: "You + a host",
    cost: "$0 – $50/mo",
    goal: "Go live with a real domain, real SSL, real observability. Set up the boring infrastructure that lets you sleep.",
    tools: [
      { nm: "Vercel", ds: "Default for Next.js, edge, preview URLs", px: "Free / $20" },
      { nm: "Netlify", ds: "Static + functions, generous free", px: "Free / $19" },
      { nm: "Cloudflare Pages", ds: "Cheap at scale, edge runtime", px: "Free / $5" },
      { nm: "Railway", ds: "Full backends with Postgres", px: "$5+ usage" },
      { nm: "Render", ds: "Heroku-like, predictable pricing", px: "Free / $7+" },
      { nm: "Fly.io", ds: "Global VMs, ship Dockerfiles", px: "Usage-based" },
      { nm: "GitHub Actions", ds: "CI/CD, free for public repos", px: "Free / $4+" },
      { nm: "Sentry", ds: "Error + perf monitoring", px: "Free / $26" },
      { nm: "PostHog", ds: "Product analytics, session replay", px: "Free / usage" },
      { nm: "Cloudflare", ds: "DNS, CDN, WAF, DDoS", px: "Free" },
      { nm: "Resend", ds: "Transactional email, dev-first", px: "Free / $20" },
    ],
    do: [
      { t: "Set up CI/CD", d: "GitHub Actions → typecheck → test → preview deploy → prod on merge to main. Manual deploys are how you ship broken things at 11pm." },
      { t: "Configure environments", d: "dev · staging · prod, each with its own database & secrets. Never edit prod directly." },
      { t: "Wire observability", d: "Sentry for errors. PostHog for product analytics. A status page (e.g. Instatus, $20)." },
      { t: "Domain, SSL, email", d: "Buy domain (Cloudflare/Porkbun). Auto-SSL via host. SPF/DKIM/DMARC for email deliverability." },
      { t: "Backup + rollback plan", d: "Daily DB backups (Supabase does this). Test restoring once. Know the 'revert deploy' button." },
    ],
    deliver: ["Live custom domain", "Auto-deploys on push", "Error tracking dashboard", "Status page", "Documented rollback"],
    pitfall: "Deploying to Vercel from the Lovable export but leaving Supabase on free tier with auto-pause. Your app goes to sleep, your users see 500s.",
  },
  {
    id: "operate",
    stage: "05",
    name: "Operate",
    time: "Ongoing",
    persona: "You + first users",
    cost: "$50 – $300/mo",
    goal: "Real users hit your app. You watch what breaks. You fix what matters and ignore what doesn't.",
    tools: [
      { nm: "Linear", ds: "Issue tracker, bug → ticket flow", px: "Free / $8" },
      { nm: "Intercom / Plain", ds: "Customer support inbox", px: "$39+ / $35" },
      { nm: "Crisp", ds: "Cheap support chat", px: "Free / $25" },
      { nm: "Slack / Discord", ds: "Internal & community", px: "Free" },
      { nm: "Better Stack", ds: "Uptime + logs, one dashboard", px: "Free / $25" },
      { nm: "Grafana Cloud", ds: "Metrics, dashboards, alerts", px: "Free / $8+" },
      { nm: "Statuspage / Instatus", ds: "Public status page", px: "$20+ / $20" },
      { nm: "Loops / Resend", ds: "Lifecycle email, onboarding drip", px: "Free / $49" },
      { nm: "Plausible / Fathom", ds: "Privacy-first web analytics", px: "$9 / $14" },
    ],
    do: [
      { t: "Daily ops loop", d: "Morning: Sentry inbox, Stripe dashboard, support inbox. 20 min, not 2 hours." },
      { t: "Talk to 3 users a week", d: "Schedule it. The AI will not tell you why people churn." },
      { t: "Weekly cost review", d: "Vercel, Supabase, OpenAI, Stripe. Cloud costs spiral when you're not looking." },
      { t: "Ship small, ship often", d: "Feature flags (PostHog, Vercel) > big releases. Roll out to 10% first." },
      { t: "Capture every escalation", d: "Every support ticket = a docs page, a bugfix, or a feature." },
    ],
    deliver: ["Runbook for top 5 incidents", "Public status page", "Weekly cost dashboard", "User interview cadence"],
    pitfall: "Ignoring Stripe failed-payment webhooks. A user pays, the webhook fails silently, the DB never grants access. Every signup becomes a support ticket. (This actually happens — common Lovable bug.)",
  },
  {
    id: "scale",
    stage: "06",
    name: "Scale",
    time: "Months 3–12",
    persona: "Small team",
    cost: "$300 – $5,000/mo",
    goal: "100 → 10,000 users. Performance, cost, and team scale together. The fragile parts of the vibe-coded core get rewritten.",
    tools: [
      { nm: "Cloudflare Workers / KV", ds: "Edge logic, global cache", px: "Free / $5+" },
      { nm: "Neon / PlanetScale", ds: "Serverless Postgres / MySQL", px: "Free / $19+" },
      { nm: "Redis (Upstash)", ds: "Sessions, queues, rate limits", px: "Free / $10+" },
      { nm: "Inngest / Trigger.dev", ds: "Background jobs, durable workflows", px: "Free / $20+" },
      { nm: "Tinybird / ClickHouse Cloud", ds: "Analytics warehouse", px: "Free / $25+" },
      { nm: "Datadog / New Relic", ds: "APM, distributed tracing", px: "$15+" },
      { nm: "k6 / Artillery", ds: "Load testing", px: "Free / $99+" },
      { nm: "LaunchDarkly / Statsig", ds: "Feature flags + experiments", px: "$10+ / Free" },
      { nm: "Algolia / Typesense", ds: "Search-as-a-service", px: "Free / $20+" },
      { nm: "Mux / Cloudflare Stream", ds: "Video infra", px: "Usage" },
    ],
    do: [
      { t: "Hunt the N+1 queries", d: "Datadog APM shows you. 1,000 records becoming 1,001 DB calls is the #1 vibe-coded perf bug." },
      { t: "Cache aggressively", d: "Edge cache for reads. Redis for session. Tag-based invalidation > TTL guessing." },
      { t: "Background everything slow", d: "Email, image processing, AI calls → Inngest/Trigger. Keep request handlers <200ms." },
      { t: "A/B test the funnel", d: "Statsig/PostHog. Don't ship copy changes on vibes." },
      { t: "Rewrite the fragile core", d: "The auth code Lovable wrote? Replace with Clerk or hand-rolled. The payment flow? Use Stripe Billing primitives, not custom logic." },
    ],
    deliver: ["P95 latency < 500ms", "APM dashboard per route", "Background job queue", "Documented scaling runbook", "Cost-per-MAU tracked"],
    pitfall: "Connection pool exhaustion. Supabase free is ~20 connections. At 5,000 users, your serverless functions each open one. You see 'too many connections' at peak. Use a pooler (Supavisor, PgBouncer).",
  },
  {
    id: "enterprise",
    stage: "07",
    name: "Enterprise",
    time: "Year 1+",
    persona: "Real team, real procurement",
    cost: "$5,000+/mo",
    goal: "Sell to companies who want SOC 2, SSO, audit logs, DPAs. The boring stuff that unlocks 10× ACVs.",
    tools: [
      { nm: "WorkOS", ds: "SSO/SAML/SCIM in days, not months", px: "Free dev / $125+" },
      { nm: "Vanta / Drata", ds: "SOC 2 / ISO 27001 automation", px: "$8k+/yr" },
      { nm: "Persona / Stripe Identity", ds: "KYC / identity verification", px: "Usage" },
      { nm: "OneTrust / Termly", ds: "Cookie consent, GDPR/CCPA, DPAs", px: "$30+ / Free" },
      { nm: "Cloudflare Zero Trust", ds: "VPN replacement, mTLS", px: "Free / $7" },
      { nm: "HashiCorp Vault / Doppler", ds: "Secrets management", px: "Free / $7+" },
      { nm: "AWS / GCP / Azure", ds: "When you outgrow PaaS", px: "Usage" },
      { nm: "Snowflake / BigQuery", ds: "Data warehouse, BI", px: "Usage" },
      { nm: "Pendo / Userflow", ds: "Product tours, in-app guides", px: "$25+" },
      { nm: "Salesforce / HubSpot", ds: "CRM, customer success", px: "$25+" },
    ],
    do: [
      { t: "Add SSO + SCIM", d: "WorkOS is the shortcut. Without SSO, no enterprise sale. With it, 10× ACV is on the table." },
      { t: "Get SOC 2 Type II", d: "Vanta/Drata automates 80%. Allow 3–6 months. Required for most procurement." },
      { t: "Write the runbooks", d: "Incident response, disaster recovery, on-call rotation. PagerDuty/Linear-on-call." },
      { t: "Multi-region + DR", d: "RPO/RPO targets. Cross-region DB replicas. Test failover annually." },
      { t: "Hire your first engineer", d: "Someone who reads the AI code and rewrites the parts that scared the audit." },
    ],
    deliver: ["SOC 2 Type II report", "SSO + SAML + SCIM", "Documented RPO/RTO", "DPA + cookie consent", "Status page with SLA"],
    pitfall: "Vendor lock-in to the vibe platform's hosted backend. If your auth/DB only runs on Lovable Cloud or Replit, enterprise procurement will ask for a self-hosting story you don't have. Plan portability from day one.",
  },
];

// ---- RECOMMENDED STACKS ----------------------------------------------
const STACKS = [
  {
    id: "nontech",
    persona: "Non-tech Founder",
    sub: "Validating an idea, no code background",
    layers: [
      { layer: "Build", pick: "Lovable", why: "Best UI polish, native Supabase, point-and-click visual editor.", alt: "Alt: Base44, YouWare" },
      { layer: "Backend", pick: "Supabase", why: "Auth, Postgres, RLS, storage in one. The default Lovable integration.", alt: "Alt: Lovable Cloud, Firebase" },
      { layer: "Deploy", pick: "Vercel", why: "One-click from GitHub. Preview URLs per branch. Free for hobby.", alt: "Alt: Netlify, Cloudflare Pages" },
      { layer: "Payments", pick: "Stripe", why: "Lovable scaffolds the integration. Webhooks verified server-side.", alt: "Alt: Lemon Squeezy (MoR)" },
      { layer: "Audit", pick: "Pro audit ($500–1.5k)", why: "70% of Lovable apps ship broken RLS. Pay someone before launch.", alt: "Alt: Aikido scanner, Escape.tech" },
    ],
    total: "$0–45/mo + audit",
  },
  {
    id: "indie",
    persona: "Indie Dev",
    sub: "Solo, ships fast, owns the code",
    layers: [
      { layer: "Editor", pick: "Cursor", why: "Composer for multi-file edits. Codebase indexing. $20/mo flat.", alt: "Alt: Windsurf, Copilot" },
      { layer: "Agent", pick: "Claude Code", why: "Terminal-first. Long-horizon refactors. Free with Claude Pro.", alt: "Alt: Aider, Cline" },
      { layer: "Framework", pick: "Next.js 15", why: "App Router, server actions, edge. What every AI tool knows best.", alt: "Alt: Astro, SvelteKit, Expo" },
      { layer: "Backend", pick: "Supabase", why: "Postgres + Auth + Storage + Edge Functions in one project.", alt: "Alt: Neon + Clerk, Convex" },
      { layer: "Deploy", pick: "Vercel", why: "Best Next.js DX, preview per PR, edge runtime included.", alt: "Alt: Cloudflare Pages (cheaper)" },
      { layer: "Monitor", pick: "Sentry + PostHog", why: "Errors + product analytics. Both have generous free tiers.", alt: "Alt: Better Stack, Datadog" },
    ],
    total: "$20–80/mo",
  },
  {
    id: "vercel",
    persona: "Vercel-Native Dev",
    sub: "Already living in Next.js + shadcn",
    layers: [
      { layer: "Prototype", pick: "v0 by Vercel", why: "Generates React + shadcn/ui components that drop into your repo cleanly.", alt: "Alt: Bolt, Lovable" },
      { layer: "Editor", pick: "Cursor", why: "Pair with v0: prompt v0 for UI, refine in Cursor with codebase context.", alt: "Alt: Claude Code" },
      { layer: "Framework", pick: "Next.js + shadcn", why: "The stack v0 outputs. Tailwind, Radix primitives, App Router.", alt: "—" },
      { layer: "Database", pick: "Neon + Drizzle", why: "Serverless Postgres branches per PR. Drizzle for type-safe queries.", alt: "Alt: Supabase, PlanetScale" },
      { layer: "Auth", pick: "Clerk", why: "Drop-in Next.js auth. Handles social, MFA, orgs out of the box.", alt: "Alt: NextAuth/Auth.js, Supabase Auth" },
      { layer: "Deploy", pick: "Vercel Pro", why: "The full Vercel stack — KV, Blob, Edge Config, Analytics included.", alt: "—" },
    ],
    total: "$60–150/mo",
  },
  {
    id: "enterprise",
    persona: "Enterprise Team",
    sub: "SOC 2, SSO, procurement-ready",
    layers: [
      { layer: "Editor", pick: "GitHub Copilot Enterprise", why: "Org-wide controls, SSO, content exclusions, audit log.", alt: "Alt: Cursor Business" },
      { layer: "Source", pick: "GitHub Enterprise", why: "Required for most enterprise procurement. Branch protections, code review.", alt: "Alt: GitLab" },
      { layer: "Cloud", pick: "AWS / GCP", why: "When you outgrow PaaS. Reserved instances, VPC, customer DPAs.", alt: "Alt: Azure, dedicated Vercel" },
      { layer: "Auth", pick: "WorkOS + Auth0", why: "SSO/SAML/SCIM for enterprise customers. Auth0 for end users.", alt: "Alt: Okta, Ping" },
      { layer: "Secrets", pick: "HashiCorp Vault", why: "Centralized secrets, dynamic credentials, audit trail.", alt: "Alt: Doppler, AWS Secrets Manager" },
      { layer: "Compliance", pick: "Vanta + OneTrust", why: "SOC 2 / ISO 27001 automation + cookie/DPA management.", alt: "Alt: Drata, Secureframe" },
    ],
    total: "$10k–50k/mo",
  },
  {
    id: "mobile",
    persona: "Mobile-First",
    sub: "iOS + Android from one codebase",
    layers: [
      { layer: "Prototype", pick: "Rork", why: "Prompts → Expo/React Native apps with native components. Mobile-first.", alt: "Alt: a0.dev, Bolt mobile mode" },
      { layer: "Framework", pick: "Expo + React Native", why: "OTA updates, EAS build, web bundle for free. AI tools handle it well.", alt: "Alt: Flutter (less AI support)" },
      { layer: "Backend", pick: "Supabase", why: "React Native SDK is excellent. Realtime + auth + storage.", alt: "Alt: Firebase, Convex" },
      { layer: "Build & ship", pick: "EAS (Expo)", why: "Build in cloud, submit to stores, OTA updates without re-review.", alt: "Alt: Codemagic, Bitrise" },
      { layer: "Push & analytics", pick: "OneSignal + PostHog", why: "Push notifications + product analytics with mobile SDKs.", alt: "Alt: Firebase Cloud Messaging" },
    ],
    total: "$25–120/mo",
  },
];

// ---- PRODUCTION CHECKLIST --------------------------------------------
const CHECK_CATS = [
  { id: "all", name: "All" },
  { id: "auth", name: "Auth & Access" },
  { id: "data", name: "Data & DB" },
  { id: "secrets", name: "Secrets" },
  { id: "pay", name: "Payments" },
  { id: "perf", name: "Performance" },
  { id: "ops", name: "Ops" },
  { id: "legal", name: "Legal" },
];

const CHECKLIST = [
  { cat: "secrets", sev: "crit", t: "No secrets in client bundle", d: "Search bundle for sk-, api_key, token. NEXT_PUBLIC_/VITE_ prefixes are exposed by design — only DB-anon keys belong there.", tools: "TruffleHog · npm audit · DevTools" },
  { cat: "auth", sev: "crit", t: "Row-level security on every table", d: "Default 'allow all' is the demo cheat. Write per-table policies. Test with anon role. ~70% of Lovable apps ship this broken.", tools: "Supabase RLS · Postgres policies" },
  { cat: "auth", sev: "crit", t: "Server-side authorization on every endpoint", d: "Never trust a frontend role flag. Every privileged endpoint re-checks identity & permission server-side.", tools: "Middleware · API guards" },
  { cat: "auth", sev: "high", t: "Password reset & MFA flows work", d: "AI tools skip these. Test reset, MFA enrollment, MFA recovery codes, session expiry.", tools: "Clerk · Auth0 · Supabase Auth" },
  { cat: "auth", sev: "high", t: "Admin routes locked down", d: "/admin, /debug, /internal — all behind auth + role check. Recursive: check sub-routes too.", tools: "Route guards · NextAuth middleware" },
  { cat: "data", sev: "crit", t: "No public DB endpoints", d: "Run: curl /api/private-data → expect 401/403. If 200 with data, you're leaking.", tools: "curl · Burp · Postman" },
  { cat: "data", sev: "high", t: "Soft deletes everywhere", d: "Hard DELETE is unrecoverable. Add deleted_at columns. Filter in queries. Compliance loves this too.", tools: "Drizzle · Prisma soft-delete" },
  { cat: "data", sev: "high", t: "Backup tested in last 30 days", d: "Daily backup ≠ working backup. Actually restore one to a staging DB. Do it before you need to.", tools: "Supabase PITR · pg_dump" },
  { cat: "data", sev: "med", t: "Input validation server-side", d: "Zod/Yup on every API input. Frontend validation is for UX, not security.", tools: "Zod · Valibot" },
  { cat: "pay", sev: "crit", t: "Stripe price validated server-side", d: "Frontend price can be edited to $0.01 in DevTools. The server must look up the price by ID.", tools: "Stripe Checkout Session · Price API" },
  { cat: "pay", sev: "crit", t: "Webhook signature verified", d: "Stripe sends a signature header. If you don't verify it, anyone can POST to grant access.", tools: "stripe.webhooks.constructEvent" },
  { cat: "pay", sev: "high", t: "Idempotency keys on charges", d: "Double-submit, retry, race condition → don't charge twice. Use idempotency-key header.", tools: "Stripe Idempotency-Key" },
  { cat: "pay", sev: "high", t: "Failed-payment webhook handled", d: "Stripe Checkout success ≠ access granted. The invoice.paid webhook is the truth. (Real Lovable bug.)", tools: "invoice.paid / .failed handlers" },
  { cat: "perf", sev: "high", t: "No N+1 queries", d: "List page with N items shouldn't make N+1 DB calls. Use joins, batch loaders, includes.", tools: "Datadog APM · Drizzle dataloader" },
  { cat: "perf", sev: "high", t: "Connection pooler in front of DB", d: "Serverless functions × cold-start = thousands of DB connections. Supabase free is ~20. Use Supavisor/PgBouncer.", tools: "Supavisor · PgBouncer · Neon pooler" },
  { cat: "perf", sev: "med", t: "Rate limiting on every public endpoint", d: "Login, signup, password reset, AI endpoints. Upstash + middleware. Per-IP + per-user.", tools: "Upstash Ratelimit · Cloudflare WAF" },
  { cat: "perf", sev: "med", t: "Background jobs for slow work", d: "Email, image processing, AI calls don't belong in request handlers. Use a queue.", tools: "Inngest · Trigger.dev · BullMQ" },
  { cat: "ops", sev: "crit", t: "Error tracking installed", d: "Sentry/Bugsnag with source maps. Real users encountering errors should not be a surprise.", tools: "Sentry · Bugsnag · Rollbar" },
  { cat: "ops", sev: "high", t: "Uptime + status page", d: "Better Stack pings every 30s. Public status page when something breaks builds trust.", tools: "Better Stack · Instatus · Statuspage" },
  { cat: "ops", sev: "high", t: "Generic error pages in prod", d: "Stack traces leak file paths, schema, version. Trigger an error → expect 'Something went wrong.'", tools: "Next.js error.tsx · custom 500" },
  { cat: "ops", sev: "high", t: "Documented rollback procedure", d: "One-click revert in Vercel/Netlify. Test the button. Know who can press it at 3am.", tools: "Vercel rollback · git revert" },
  { cat: "ops", sev: "med", t: "CI runs typecheck, tests, audit", d: "GitHub Actions: tsc --noEmit, vitest, npm audit. Block merge on red.", tools: "GitHub Actions · CircleCI" },
  { cat: "ops", sev: "med", t: "Dependency audit weekly", d: "AI ships old packages. Dependabot/Renovate auto-PRs. Don't ignore them for months.", tools: "Dependabot · Renovate · Snyk" },
  { cat: "legal", sev: "high", t: "Privacy policy + ToS live", d: "Required by Stripe, App Store, Play Store, GDPR. Termly/iubenda generate for $0–10/mo.", tools: "Termly · iubenda · GetTerms" },
  { cat: "legal", sev: "high", t: "Cookie consent (EU users)", d: "GDPR requires explicit opt-in for analytics. CookieYes/OneTrust banners.", tools: "CookieYes · OneTrust" },
  { cat: "legal", sev: "med", t: "Data deletion endpoint", d: "GDPR/CCPA: users can request deletion. Build it before someone emails asking for it.", tools: "Manual + soft-delete plumbing" },
  { cat: "legal", sev: "med", t: "DPA & sub-processor list", d: "Enterprise customers ask. List Vercel, Supabase, OpenAI, Stripe — every vendor that sees user data.", tools: "Vanta · Drata · static page" },
];

// ---- INCIDENTS / CAUTIONARY TALES ------------------------------------
const INCIDENTS = [
  {
    name: "Moltbook",
    tag: "Feb 2026 · Wiz Research",
    sub: "Social network, fully vibe-coded backend",
    body: "API endpoints returned sensitive data without checking authorization. Result: 1.5 million authentication tokens and 35,000 user emails exposed.",
    impact: "Lesson: server-side authz is not optional. Frontend role checks are decoration.",
  },
  {
    name: "Lovable RLS Disclosure",
    tag: "CVE-2025-48757",
    sub: "1 in 10 Lovable apps shipping with broken RLS",
    body: "Of 1,645 Lovable production apps scanned, 170 had missing or 'allow all' Row-Level Security policies — exposing real user data to the public internet.",
    impact: "Lesson: 'It works in the demo' is the entire problem. RLS demo-mode defaults are not production-safe.",
  },
  {
    name: "Lovable Exam App",
    tag: "Escape.tech audit",
    sub: "16 vulnerabilities, 6 critical",
    body: "An education app, fully vibe-coded, exposed 18,697 users including university students. Auth logic was inverted: unauthenticated visitors got access. RLS misconfigured.",
    impact: "Lesson: every auth check needs a negative test. 'Logged-in users see X' is half the story; 'logged-out users see nothing' is the other half.",
  },
  {
    name: "The 400+ Secrets Sweep",
    tag: "Escape.tech · 5,600 apps",
    sub: "Stripe keys, Supabase JWTs, OpenAI tokens in browser bundles",
    body: "Across 5,600+ vibe-coded apps scanned, 400+ live secrets were found embedded in frontend JS — indexable by Google, scrapable by anyone.",
    impact: "Lesson: NEXT_PUBLIC_ and VITE_ prefixes are PUBLIC. Audit your bundle before every deploy.",
  },
  {
    name: "The Stripe Webhook Gap",
    tag: "Beesoul audit",
    sub: "Charging users, not granting access",
    body: "A Lovable-built SaaS charged users correctly but never granted access — because the success page updated the UI while a silently-failing webhook left the DB untouched. Every paid signup became a manual support ticket.",
    impact: "Lesson: the Stripe success URL is a hint. The invoice.paid webhook is the truth.",
  },
  {
    name: "The 50 → 5,000 Cliff",
    tag: "The New Stack",
    sub: "Scaling failure pattern",
    body: "Quote: 'At 50 users this is fine, at 5,000 it's a liability, and at 50,000 it's an incident.' Root causes AI doesn't generate: N+1 queries, connection pool exhaustion, no rate limiting, no monitoring.",
    impact: "Lesson: load-test before you launch. k6 is free. Find the breaking point on staging, not on Hacker News front page.",
  },
];

// ---- HERO STATS ------------------------------------------------------
const STATS = [
  { v: "46", u: "%", l: "of new code is AI-generated (GitHub, 2026)" },
  { v: "92", u: "%", l: "of US devs use AI tools daily" },
  { v: "45", u: "%", l: "of AI code has OWASP Top 10 vulns (Veracode)" },
  { v: "$4.7", u: "B", l: "vibe coding market in 2026 (Taskade)" },
];

// ---- ALL TOOLS (master index, auto-flattened from above) -------------
const TOOL_INDEX = [
  // Tier 1
  { nm: "Claude", cat: "AI Chat", tier: "T1", px: "Free / $20", ds: "Anthropic's flagship. Best for code reasoning, long context." },
  { nm: "ChatGPT", cat: "AI Chat", tier: "T1", px: "Free / $20", ds: "OpenAI. Broad ecosystem, plugins, Canvas mode." },
  { nm: "Gemini", cat: "AI Chat", tier: "T1", px: "Free / $20", ds: "Google. 2M context window, Workspace integration." },
  { nm: "Manus", cat: "AI Chat", tier: "T1", px: "Free / $20", ds: "Wide research + computer-use agent." },
  { nm: "Grok", cat: "AI Chat", tier: "T1", px: "$8 / $30", ds: "xAI. Real-time X integration." },
  // Tier 2
  { nm: "Lovable", cat: "Vibe Platform", tier: "T2", px: "Free / $25", ds: "Best UI polish. Native Supabase. Non-technical default." },
  { nm: "Bolt.new", cat: "Vibe Platform", tier: "T2", px: "Free / $20", ds: "Fastest browser → app. StackBlitz WebContainer." },
  { nm: "v0 by Vercel", cat: "Vibe Platform", tier: "T2", px: "Free / $20", ds: "React + shadcn components. Vercel-native." },
  { nm: "Replit Agent", cat: "Vibe Platform", tier: "T2", px: "Free / $25", ds: "Browser IDE + agent. Broad language support." },
  { nm: "Rork", cat: "Vibe Platform", tier: "T2", px: "Free / $20", ds: "Mobile-first. Prompts → Expo apps." },
  { nm: "Base44", cat: "Vibe Platform", tier: "T2", px: "Free / $20", ds: "Enterprise-leaning, internal tools." },
  { nm: "Emergent", cat: "Vibe Platform", tier: "T2", px: "$20+", ds: "Multi-agent full-product builder." },
  { nm: "Tempo Labs", cat: "Vibe Platform", tier: "T2", px: "$25+", ds: "Design-first React builder." },
  { nm: "Firebase Studio", cat: "Vibe Platform", tier: "T2", px: "Free", ds: "Google's vibe-coding entry, Firebase-native." },
  { nm: "a0.dev", cat: "Vibe Platform", tier: "T2", px: "Free / $20", ds: "Mobile-first, similar to Rork." },
  // Tier 3
  { nm: "Cursor", cat: "AI Editor", tier: "T3", px: "$20 / $40", ds: "Default AI IDE. Composer, Tab, codebase indexing." },
  { nm: "Windsurf", cat: "AI Editor", tier: "T3", px: "Free / $15", ds: "Codeium's IDE. Cascade agent, flat pricing." },
  { nm: "GitHub Copilot", cat: "AI Editor", tier: "T3", px: "$10 / $19", ds: "Cheapest. IDE-agnostic. Org-wide controls." },
  { nm: "Trae", cat: "AI Editor", tier: "T3", px: "Free", ds: "ByteDance. Free during early access with Claude + GPT." },
  { nm: "Zed", cat: "AI Editor", tier: "T3", px: "Free / $20", ds: "Fast Rust-built editor. Multi-buffer AI." },
  { nm: "Voibe", cat: "Input Layer", tier: "T3", px: "$99 once", ds: "Offline voice → prompt. 3–5× prompting speed." },
  // Tier 4
  { nm: "Claude Code", cat: "Agent CLI", tier: "T4", px: "Bundled", ds: "Terminal-first agent. Long-horizon multi-file work." },
  { nm: "Warp.dev", cat: "Terminal", tier: "T4", px: "Free / $15", ds: "AI-native terminal. Agent mode for shell ops." },
  { nm: "Aider", cat: "Agent CLI", tier: "T4", px: "Free + API", ds: "OSS CLI pair programmer. Git-native." },
  { nm: "Gemini CLI", cat: "Agent CLI", tier: "T4", px: "Free", ds: "Google's CLI agent. Free with Google account." },
  { nm: "Cline", cat: "Agent CLI", tier: "T4", px: "Free + API", ds: "VS Code extension. BYO API key." },
  // Tier 5
  { nm: "Devin", cat: "Autonomous", tier: "T5", px: "$20+", ds: "Cognition AI. Dropped from $500 to $20 in 2026." },
  { nm: "OpenClaw", cat: "Autonomous", tier: "T5", px: "$25+", ds: "Multi-day async engineering tasks." },
  { nm: "Manus Agents", cat: "Autonomous", tier: "T5", px: "$20+", ds: "Computer-use + browser automation." },
  { nm: "NVIDIA NeMo Agents", cat: "Autonomous", tier: "T5", px: "Enterprise", ds: "Enterprise agent framework." },
  // Backend
  { nm: "Supabase", cat: "Backend", tier: "BaaS", px: "Free / $25", ds: "Postgres + Auth + Storage + RLS. Vibe-default." },
  { nm: "Firebase", cat: "Backend", tier: "BaaS", px: "Free / Usage", ds: "Google. NoSQL. Strong mobile SDKs." },
  { nm: "Convex", cat: "Backend", tier: "BaaS", px: "Free / $25", ds: "Reactive backend with TypeScript functions." },
  { nm: "Neon", cat: "Database", tier: "DB", px: "Free / $19", ds: "Serverless Postgres. DB branches per PR." },
  { nm: "PlanetScale", cat: "Database", tier: "DB", px: "$39+", ds: "Serverless MySQL. Branching workflow." },
  { nm: "Upstash", cat: "Cache/Queue", tier: "DB", px: "Free / $10", ds: "Serverless Redis + Kafka. Pay-per-request." },
  // Auth
  { nm: "Clerk", cat: "Auth", tier: "Auth", px: "Free / $25", ds: "Drop-in auth for Next.js, React. MFA, orgs." },
  { nm: "Auth0", cat: "Auth", tier: "Auth", px: "Free / $35+", ds: "Enterprise auth. Now part of Okta." },
  { nm: "WorkOS", cat: "Auth", tier: "Auth", px: "Free dev / $125+", ds: "SSO/SAML/SCIM in days. Enterprise unlock." },
  { nm: "NextAuth / Auth.js", cat: "Auth", tier: "Auth", px: "Free", ds: "OSS, self-hosted, framework-agnostic." },
  // Payments
  { nm: "Stripe", cat: "Payments", tier: "Pay", px: "2.9%+30¢", ds: "Default. Best DX. Every AI tool knows it." },
  { nm: "Lemon Squeezy", cat: "Payments", tier: "Pay", px: "5%+50¢", ds: "Merchant of record. Handles VAT/sales tax." },
  { nm: "Paddle", cat: "Payments", tier: "Pay", px: "5%+50¢", ds: "MoR alternative. Strong on SaaS." },
  { nm: "Polar", cat: "Payments", tier: "Pay", px: "4%+40¢", ds: "Modern MoR, dev-tool friendly." },
  // Hosting
  { nm: "Vercel", cat: "Hosting", tier: "Host", px: "Free / $20", ds: "Default for Next.js. Edge, preview URLs." },
  { nm: "Netlify", cat: "Hosting", tier: "Host", px: "Free / $19", ds: "Static + functions. Generous free tier." },
  { nm: "Cloudflare Pages", cat: "Hosting", tier: "Host", px: "Free / $5", ds: "Cheap at scale. Workers edge runtime." },
  { nm: "Railway", cat: "Hosting", tier: "Host", px: "$5+ usage", ds: "Heroku-like. Full backends with Postgres." },
  { nm: "Render", cat: "Hosting", tier: "Host", px: "Free / $7+", ds: "Predictable pricing. Background workers." },
  { nm: "Fly.io", cat: "Hosting", tier: "Host", px: "Usage", ds: "Global VMs. Ship Dockerfiles to 30+ regions." },
  // Monitoring
  { nm: "Sentry", cat: "Monitoring", tier: "Obs", px: "Free / $26", ds: "Errors + perf + session replay." },
  { nm: "PostHog", cat: "Analytics", tier: "Obs", px: "Free / Usage", ds: "Product analytics, feature flags, replays." },
  { nm: "Better Stack", cat: "Monitoring", tier: "Obs", px: "Free / $25", ds: "Uptime + logs in one dashboard." },
  { nm: "Datadog", cat: "Monitoring", tier: "Obs", px: "$15+", ds: "Enterprise APM, traces, infra." },
  { nm: "Plausible", cat: "Analytics", tier: "Obs", px: "$9+", ds: "Privacy-first web analytics. GDPR-safe." },
  // Security
  { nm: "Aikido", cat: "Security", tier: "Sec", px: "Free / $25", ds: "Vibe-code specific scanner. SAST + SCA." },
  { nm: "Escape.tech", cat: "Security", tier: "Sec", px: "Free tier", ds: "DAST + AI-app security scanning." },
  { nm: "TruffleHog", cat: "Security", tier: "Sec", px: "Free", ds: "Scan git history for leaked secrets." },
  { nm: "Snyk", cat: "Security", tier: "Sec", px: "Free / $25", ds: "Dependency vulns, container, IaC." },
  { nm: "Dependabot", cat: "Security", tier: "Sec", px: "Free", ds: "GitHub-native auto dependency PRs." },
  // Compliance
  { nm: "Vanta", cat: "Compliance", tier: "Ent", px: "$8k+/yr", ds: "SOC 2 / ISO 27001 automation." },
  { nm: "Drata", cat: "Compliance", tier: "Ent", px: "$8k+/yr", ds: "Vanta alternative. Strong audit prep." },
  { nm: "OneTrust", cat: "Compliance", tier: "Ent", px: "$30+", ds: "Cookie consent, DPA, privacy ops." },
  // Background jobs
  { nm: "Inngest", cat: "Jobs", tier: "Inf", px: "Free / $20+", ds: "Durable workflows. AI-friendly steps." },
  { nm: "Trigger.dev", cat: "Jobs", tier: "Inf", px: "Free / $20+", ds: "Long-running background jobs in TS." },
  // Email
  { nm: "Resend", cat: "Email", tier: "Inf", px: "Free / $20", ds: "Transactional email. React Email templates." },
  { nm: "Loops", cat: "Email", tier: "Inf", px: "Free / $49", ds: "Lifecycle & marketing email." },
  // CMS
  { nm: "Sanity", cat: "CMS", tier: "Inf", px: "Free / $15+", ds: "Structured content. Real-time collab." },
  { nm: "Contentful", cat: "CMS", tier: "Inf", px: "Free / $300+", ds: "Enterprise headless CMS." },
];
